# Cálculo da inversa de uma matriz

Seja A $\in$ $\mathbb{M}_n(\mathbb{R})$

$$A^{-1} = [v_1 v_2 \cdots v_n]$$
Em que $v_k$ são as colunas da matriz inversa.

Assim,

$$A A^{-1} = I$$

$$A\begin{bmatrix}
v_1 & v_2 & \cdots & v_n \\
\end{bmatrix} = \begin{bmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
e_1 & e_2 & \cdots & e_n \\
\vdots & \cdots & \ddots & \vdots \\
0 & 0 & \cdots & 1\\\
\end{bmatrix}$$

Logo, basta resolver $n$ sistemas lineares $A \cdot v_i = e_i$, $i = 1, \cdots, n$

Por exemplo, com $n = 3$, podemos resolver a primeira coluna da matriz inversa da seguinte forma:

$$\begin{bmatrix}
A_{11} & A_{12} & A_{13} \\
A_{21} & A_{22} & A_{23} \\
A_{31} & A_{32} & A_{33} \\
\end{bmatrix} \begin{bmatrix}
a^{'}_{11} \\
a^{'}_{21} \\
a^{'}_{31} \\
\end{bmatrix} = \begin{bmatrix}
1 \\
0 \\
0 \\
\end{bmatrix}$$

De forma análoga, para resolver a segunda coluna, calculamos o resultado de $Av^{'}_2 = [0, 1, 0]^T$, e assim por diante.

In [2]:
import numpy as np
from ipynb.fs.full.LU import *

In [3]:
def inverse_matrix(A):
    n = A.shape[0]
    
    Inv = np.zeros_like(A)
    Id = np.eye(n)
    
    for k in range(0, n):
        Inv[:, k] = lu_solve_partial_pivot(A, Id[:, k])
    
    return Inv

In [8]:
A = np.array([[1, 2, 0], [1, 3, 1], [-2, 0, 1]]).astype('float64')
print(inverse_matrix(A))

print(np.linalg.inv(A)) # caso queira comparar com o correto

[[-1.          0.66666667 -0.66666667]
 [ 1.         -0.33333333  0.33333333]
 [-2.          1.33333333 -0.33333333]]
[[-1.          0.66666667 -0.66666667]
 [ 1.         -0.33333333  0.33333333]
 [-2.          1.33333333 -0.33333333]]
