In [27]:
import numpy as np

# Métodos iterativos
Seja $Ax = b$ um sistema linear de ordem $n$, com $det(A) \neq 0$.

### Objetivo
Queremos definir um processo iterativo, de modo que a sequência de vetores {${x^{(0)}, x^{(1)}, x^{(2)}, \cdots}$} produzida por este processo convirja para a solução $x$, independentemente do chute inicial $x^{(0)} \in \mathbb{R}^n$.

### Definição
Uma sequência de vetores {${x^{(0)}, x^{(1)}, x^{(2)}, \cdots}$} converge para um vetor $x$ se $\lim_{k \rightarrow +\infty}{|| x^{(k)} - x ||} = 0$

**Notação:** $x^{(k)} \rightarrow x$

### Ideia principal
vamos criar um processo recursivo através de um sistema equivalente $Ax = b$

1. Transformar $Ax = b$ em um sistema equivalente da forma $x = Cx + g$, em que $C \in \mathbb{M}_n(\mathbb{R})$ e $g \in \mathbb{R}^n$ são conhecidos

2. Dado um chute inicial $x^{(0)}$, obtemos uma sequência {${x^{(0)}, x^{(1)}, x^{(2)}, \cdots}$}  através do processo iterativo $x^{(k+1)} = Cx^{(k)} + g$, com k = 0, 1, ...

### Perguntas
- Dado $Ax = b$ é possível obter um sistema equivalente $x = Cx + g$?
  
  Sim, por exemplo, basta tomar $C = I - A$ e $g = b$
  
  
- Se $x^{(k)} \rightarrow \bar{x}$, então $\bar{x}$ é solução de $Ax = b$?

  Sim, pois passando o limite no processo iterativo $x^{(k+1)} = Cx^{(k)} + g$, temos $\bar{x} = C\bar{x} + g$. Como os sistemas são equivalentes, $\bar{x} = x$, $A\bar{x} = b$
  
  
- Quando terminar o processo iterativo {${x^{(0)}, x^{(1)}, x^{(2)}, \cdots}$}?
  
  Vários critérios, pela distância relativa entre os chutes, por um valor de iterações máximo, etc

### Critérios de parada
Dados $\epsilon > 0$ e $K_{max} \in \mathbb{N}$

#### Erro absoluto
$$ || x^{(k+1)} - x^{(k)} || < \epsilon $$

#### Erro relativo
$$ \frac{|| x^{(k+1)} - x^{(k)} ||}{||x^{(k+1)}||} < \epsilon $$

#### Teste do resíduo
$$ || b - Ax^{(k)}|| < \epsilon $$

#### Número máximo de iterações
$$ while(k < K_{max}) $$

## Convergência

#### Definição (Raio espectral)
Raio espectral de uma matriz $A \in \mathbb{M}_n(\mathbb{R})$ é definido como $\rho(A)$ = máx{ |$\lambda_i$| }, onde $\lambda_i$ são os autovalores de A.

#### Teorema (Critério geral de convergência)
Seja {${x^{(0)}, x^{(1)}, x^{(2)}, \cdots}$} sequência gerada pelo processo iterativo $x^{(k+1)} = Cx^{(k)} + g$,

1. Se $||C||_M < 1$, onde $||.||_m$ é uma norma consistente, então a sequência converge.

2. $x^{(k)} \rightarrow x \iff \rho(C) < 1$

## Método de Gauss-Jacobi

Dado $Ax = b$ e supondo sem perda de generalidade que $a_{ii} \neq 0$, com $i = 1,\cdots,n$, temos:

$$\begin{cases}
a_{11}x_1 + a_{12}x_2 + \cdots + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \cdots + a_{2n}x_n = b_2 \\
\vdots \\
a_{n1}x_1 + a_{n2}x_2 + \cdots + a_{nn}x_n = b_n \\
\end{cases} $$

A forma do método de Gauss-Jacobi transforma $Ax = b$ em $x = Cx + g$ isolando cada coordenada $x_i$ do vetor $x$

$$\begin{cases}
x^{(k+1)}_1 = \frac{b_1 - a_{12}x^{(k)}_2 - a_{13}x^{(k)}_3 - \cdots - a_{1n}x^{(k)}_n}{a_{11}} \\
x^{(k+1)}_2 = \frac{b_2 - a_{21}x^{(k)}_1 - a_{23}x^{(k)}_3 - \cdots - a_{2n}x^{(k)}_n}{a_{22}} \\
\vdots \\
x^{(k+1)}_n = \frac{b_n - a_{n1}x^{(k)}_1 - a_{n2}x^{(k)}_2 - \cdots - a_{n-1 n-1}x^{(k)}_{n-1}}{a_{nn}} \\
\end{cases} $$

Desta forma, temos um sistema equivalente $x = Cx + g$ em que:

$$C = \begin{bmatrix}
0 & -\frac{a_{12}}{a_{11}} & \cdots & -\frac{a_{1n}}{a_{11}} \\
-\frac{a_{21}}{a_{22}} & 0 & \vdots & -\frac{a_{2n}}{a_{22}} \\
\vdots & \ddots & \ddots & \vdots \\
-\frac{a_{n1}}{a_{nn}} & \cdots & 0 & -\frac{a_{2n}}{a_{22}} \\
\end{bmatrix}, g = \begin{bmatrix}
\frac{b_1}{a_{11}} \\
\frac{b_2}{a_{22}} \\
\vdots \\
\frac{b_n}{a_{nn}} \\
\end{bmatrix}$$

Vamos mostrar como obter $x^{(k+1)} = Cx^{(k)} + g$ a partir de $Ax = b$.

Seja D uma matriz diagonal, formada pela diagonal de A.

$$Ax = b \iff (A + D - D)x = b \iff (A - D)x + Dx = b$$

Dessa forma,

$$ (A - D)x^{(k)} + Dx^{(k+1)} = (D - A)x^{(k)} + b $$

Portanto,

$$ x^{(k+1)} = \underbrace{(I - D^{-1}A)}_{C}x^{(k)} + \underbrace{D^{-1}b}_{g} $$

In [28]:
# Resolve o sistema $Ax = b$ pelo método interativo de Gauss-Jacobi e critério de parada do erro relativo
def gauss_jacobi_solve(A, b, EPSILON=1e-8):
    n = A.shape[0]
    x = np.zeros_like(b) # x^{k+1}
    _x = np.full(n, 1)   # x^{k}
    
    D = np.eye(n) * A    
    D_i = np.linalg.inv(D)
    I = np.eye(n)
    
    C = I - D_i @ A
    g = D_i @ b
    
    while np.linalg.norm(x - _x)/np.linalg.norm(x) > EPSILON:
        _x = x
        x = C @ x + g

    return x

In [29]:
A = np.array([[8, 1, -1], [1, -7, 2], [2, 1, 9]]).astype('float64')
b = np.array([8, -4, 2]).astype('float64')

x = gauss_jacobi_solve(A, b)
print(x)

[ 0.90740741  0.68518518 -0.05555555]


## Método de Gauss-Seidel

Tentaremos agora acelerar a convergência do Método de Gauss-Jacobi. No cálculo de $x_i^{(k+1)}$, usaremos os valores já calculados $x_j^{(k+1)}, j < i$ os valores que ainda não foram calculados $x_j^{(k)}, j > i$.


$$\begin{cases}
x^{(k+1)}_1 = \frac{b_1 - a_{12}x^{(k)}_2 - a_{13}x^{(k)}_3 - \cdots - a_{1n}x^{(k)}_n}{a_{11}} \\
x^{(k+1)}_2 = \frac{b_2 - a_{21}x^{(k+1)}_1 - a_{23}x^{(k)}_3 - \cdots - a_{2n}x^{(k)}_n}{a_{22}} \\
\vdots \\
x^{(k+1)}_n = \frac{b_n - a_{n1}x^{(k+1)}_1 - a_{n2}x^{(k+1)}_2 - \cdots - a_{n-1 n-1}x^{(k+1)}_{n-1}}{a_{nn}} \\
\end{cases} $$

Para obter $x^{(k+1)} = Cx^{(k)} + g$ a partir de $Ax + b$, primeiramente consideremos $A = L + R$, em que $L$ é a matriz triangular inferior de $A$ e $R$ é a matriz triangular superior sem a diagonal principal. Assim:

$$Ax = b \iff (L+R)x = b \iff Lx + Rx = b$$

Dessa forma,
$$Lx^{(k+1)} + Rx^{(k)} = b \iff Lx^{(k+1)} = -Rx^{(k)} + b$$

Portanto,

$$ x^{(k+1)} = \underbrace{(-L^{-1}R)}_{C}x^{(k)} + \underbrace{L^{-1}b}_{g} $$

In [30]:
# Resolve o sistema $Ax = b$ pelo método interativo de Gauss-Seidel e critério de parada do erro relativo
def gauss_seidel_solve(A, b, EPSILON=1e-8):
    n = A.shape[0]
    x = np.zeros_like(b) # x^{k+1}
    _x = np.full(n, 1)   # x^{k}
    
    L = np.tril(A)
    R = np.triu(A, 1)
    
    L_i = np.linalg.inv(L)
    C = -L_i @ R
    g = L_i @ b
    
    while np.linalg.norm(x - _x)/np.linalg.norm(x) > EPSILON:
        _x = x
        x = C @ x + g
        
    return x

In [31]:
A = np.array([[8, 1, -1], [1, -7, 2], [2, 1, 9]]).astype('float64')
b = np.array([8, -4, 2]).astype('float64')

x = gauss_seidel_solve(A, b)
print(x)

[ 0.90740741  0.68518519 -0.05555556]


## Aplicações

Suponha a seguinte placa, já em temperatura de equilíbrio. Ao discretizá-la com uma grade, qual o valor da temperatura nos pontos $x_i, i=1,2,3,4$ sendo que a temperatura em um ponto é a média da temperatura em seus vizinhos?

![Grade](./img/grade_temperatura.png)

$$\begin{cases}
x_1 = \frac{20 + 25 + x_2 + x_3}{4}\\
x_2 = \frac{x_1 + 25 + 30 + x_4}{4}\\
x_3 = \frac{20 + x_1 + x_4 + 20}{4}\\
x_4 = \frac{x_3 + x_2 + 30 + 20}{4}
\end{cases} $$

Disso, formamos o seguinte sistema de matrizes:

$$
\begin{bmatrix}
4 & -1 & -1 & 0\\
-1 & 4 & 0 & -1\\
-1 & 0 & 4 & -1\\
0 & -1 & -1 & 4
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4
\end{bmatrix}
= \begin{bmatrix}
45\\
55\\
40\\
50
\end{bmatrix}
$$

Sua resolução pode ser feita da seguinte forma:

In [32]:
A = np.array([[4, -1, -1, 0], [-1, 4, 0, -1], [-1, 0, 4, -1], [0, -1, -1, 4]]).astype('float64')
b = np.array([45, 55, 40, 50])
print(gauss_seidel_solve(A, b))

[23.12499993 25.62499997 21.87499997 24.37499998]


Dada uma placa quadrada de lado *[0, 1] × [0, 1]* metros, já com os valores de temperatura prescritos na fronteira. Faça uma função que calcule e visualize a distribuição de temperaturas nesta placa usando o Método de Gauss-Seidel e um grid de resolução n × n.

In [33]:
# dado um par [i, j] retorna sua ordem (0, 1, 2, 3...)
def get(i, j, n, m):
    return j * n + i

# sides sao os valores pre definidos [left, up, right, down]
def placa_quadrada_solve(sides, n, m):
    A = np.zeros((n*m, n*m))
    b = np.zeros(n*m)
    
    # percorre todas as celulas preenchendo a matriz A ao procurar seus vizinhos
    for i in range(n):
        for j in range(m):
            at = get(i, j, m, m)
            A[at, at] = 4
            
            u = get(i-1, j, n, m)
            d = get(i+1, j, n, m)
            l = get(i, j-1, n, m)
            r = get(i, j+1, n, m)
            
            if j-1 < 0:
                b[at] += sides[0] # celula esquerda eh vizinha
            else:
                A[at, l] = -1
                
            if i-1 < 0:
                b[at] += sides[1] # celula superior eh vizinha
            else:
                A[at, u] = -1
                
            if j+1 >= m:
                b[at] += sides[2] # celular direita eh vizinha
            else:
                A[at, r] = -1
                
            if i+1 >= n:
                b[at] += sides[3] # celula inferior eh vizinha
            else:
                A[at, d] = -1           
    
    return gauss_seidel_solve(A, b)
        
placa_quadrada_solve([25, 20, 20, 30], 2, 2)

array([23.12499993, 25.62499997, 21.87499997, 24.37499998])